### ISSUE TITLE
allow arrays in metadata

### ISSUE THREAD

**Issue by tacman** [zenstruck/class-metadata#4]
What a great plug-in, thanks!

> Metadata values must be scalar (bool|float|int|string).

Can you allow arrays, since PHP supports array constants?  I found myself needing to associate a list of possible tags with a class..

```php
#[Metadata('actions', 'list,check,clean')]

class MyClass {
    const ACTIONS=['list,'check','clean']; // replace this with metadata call
```

Of course, I guess another approach would be Enums, which I should probably use more than I do...

There's probably a good reason why these are scalar, but I figured I'd ask the question anyway.

**Comment by kbond** [comment]
I don't think it'd be an issue to support arrays. As long as the data can be var_exported it should work.

I believe anything that can be added to an attribute should be valid.
